### ISSUE TITLE
Не выходит с mintmanga.com.

### ISSUE THREAD

**Issue by Vadimatorik** [4ndv/mrmanga#3]
Здравствуйте. Использую Ubuntu 16.04. Установил ruby-full. Приложение успешно установилось, запустилось. Попытался скачать целиком мангу согласно инструкции с адреса `http://mintmanga.com/sekirei`
Получил:
`~/Загрузки/manga$ mrmanga 
Welcome to mrmanga 0.8.0!
It will create folders into CURRENT PATH!!
Tell me the link of the manga you want to download (example: http://readmanga.me/your_name)?  http://mintmanga.com/sekirei        
Just press Enter to download all the volumes, or specity volumes using this: 1-5 or this: 1, 2, 3, 4, 5 (or 1,2,3,4,5) syntaxes. Also you can download one volume by entering it's number (like this: 1)
Which volumes should i download?  |all|  
How many threads should i use to download? (6)  1
Create pdfs for volumes?  |yes|

Add pages in PDF outline?  |yes|

Parsing manga info
/var/lib/gems/2.3.0/gems/mrmanga-0.8.0/lib/mrmanga/parser.rb:33:in `block in get_manga': Wrong url: /sekirei/vol1/-1?mtr= (RuntimeError)
	from /var/lib/gems/2.3.0/gems/mrmanga-0.8.0/lib/mrmanga/parser.rb:30:in `map!'
	from /var/lib/gems/2.3.0/gems/mrmanga-0.8.0/lib/mrmanga/parser.rb:30:in `get_manga'
	from /var/lib/gems/2.3.0/gems/mrmanga-0.8.0/lib/mrmanga/cli.rb:58:in `interactive_shell'
	from /var/lib/gems/2.3.0/gems/mrmanga-0.8.0/exe/mrmanga:5:in `<top (required)>'
	from /usr/local/bin/mrmanga:23:in `load'
	from /usr/local/bin/mrmanga:23:in `<main>'`

**Comment by Vadimatorik** [comment]
Заметил, что http://mintmanga.com/elfen_lied качается нормально. Есть подозрение на то, что дело в том, что в предыдущей манге главы нумеруются с -2.

**Comment by 4ndv** [comment]
Да, скорее всего, дело именно в "отрицательной" нумерации. Постараюсь сегодня вечером продебажить этот момент

**Comment by 4ndv** [comment]
Подозреваю, что тут все весьма понятно, нужно просто поправить регексп тут:

https://github.com/4ndv/mrmanga/blob/4c18a3672e0746e60b18ed6b9e497414979f277c/lib/mrmanga/parser.rb#L28

Вечером (если не забуду) починю и залью новую версию

**Comment by 4ndv** [comment]
Залил обновление, вроде как всё ок. Обновить установленную версию можно этой командой:

```bash
(sudo) gem install mrmanga
```

Если снова возникнет эта проблема - просто переоткройте эту ишшую (:
