### ISSUE TITLE
Проблемы при установке в Arch Linux.

### ISSUE THREAD

**Issue by Vadimatorik** [4ndv/mrmanga#4]
Установка. 
```
[vadimatorik@vadimatorikpc ~]$ sudo  gem install mrmanga
[sudo] пароль для vadimatorik: 
Fetching: highline-1.7.10.gem (100%)
WARNING:  You don't have /root/.gem/ruby/2.5.0/bin in your PATH,
	  gem executables will not run.
Successfully installed highline-1.7.10
Fetching: nokogiri-1.8.4.gem (100%)
Building native extensions. This could take a while...
Successfully installed nokogiri-1.8.4
Fetching: ttfunk-1.5.1.gem (100%)
Successfully installed ttfunk-1.5.1
Fetching: pdf-core-0.7.0.gem (100%)
Successfully installed pdf-core-0.7.0
Fetching: prawn-2.2.2.gem (100%)
Successfully installed prawn-2.2.2
Fetching: down-4.5.0.gem (100%)
Successfully installed down-4.5.0
Fetching: parallel-1.12.1.gem (100%)
Successfully installed parallel-1.12.1
Fetching: mini_magick-4.8.0.gem (100%)
Successfully installed mini_magick-4.8.0
Fetching: progressbar-1.10.0.gem (100%)
Successfully installed progressbar-1.10.0
Fetching: mrmanga-0.9.0.gem (100%)
Successfully installed mrmanga-0.9.0
Parsing documentation for highline-1.7.10
Installing ri documentation for highline-1.7.10
Parsing documentation for nokogiri-1.8.4
Installing ri documentation for nokogiri-1.8.4
Parsing documentation for ttfunk-1.5.1
Installing ri documentation for ttfunk-1.5.1
Parsing documentation for pdf-core-0.7.0
Installing ri documentation for pdf-core-0.7.0
Parsing documentation for prawn-2.2.2
Installing ri documentation for prawn-2.2.2
Parsing documentation for down-4.5.0
Installing ri documentation for down-4.5.0
Parsing documentation for parallel-1.12.1
Installing ri documentation for parallel-1.12.1
Parsing documentation for mini_magick-4.8.0
Installing ri documentation for mini_magick-4.8.0
Parsing documentation for progressbar-1.10.0
Installing ri documentation for progressbar-1.10.0
Parsing documentation for mrmanga-0.9.0
Installing ri documentation for mrmanga-0.9.0
Done installing documentation for highline, nokogiri, ttfunk, pdf-core, prawn, down, parallel, mini_magick, progressbar, mrmanga after 57 seconds
10 gems installed
```
Все доступные пакеты rubi-* - установлены.

**Comment by Vadimatorik** [comment]
Полагаю, надо с путем разобраться. Которого нет в Arch Linux из коробки.

**Comment by 4ndv** [comment]
Именно так

**Comment by Vadimatorik** [comment]
Включите этот момент в скрипт установки? Т.к. это должно быть автоматически.

**Comment by 4ndv** [comment]
Проблема в вашем арче, не в моем геме. В PATH нет папки rubygems, это должен делать ваш менеджер пакетов при установке ruby.

**Comment by Vadimatorik** [comment]
Решение можно найти здесь. 
https://wiki.archlinux.org/index.php/Ruby
В моем случае нужно было добавить в файл ~/.profile строку:
`PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"`

**Comment by leoyim** [comment]
I have the same problem, but I can't understand Russian.

**Comment by 4ndv** [comment]
> I have the same problem, but I can't understand Russian.

Actually, it's a problem with your Ruby installation. You should add your rubygems binaries folder (you can see it in the error message) to your PATH variable

**Comment by 4ndv** [comment]
And if you don't understand russian, why do you need to download anything from readmanga/mintmanga? Is there any non-russian manga on them?

**Comment by leoyim** [comment]
> > I have the same problem, but I can't understand Russian.
> 
> Actually, it's a problem with your Ruby installation. You should add your rubygems binaries folder (you can see it in the error message) to your PATH variable

Thank you very much! I will have a try.

**Comment by leoyim** [comment]
> And if you don't understand russian, why do you need to download anything from readmanga/mintmanga? Is there any non-russian manga on them?

I just have a problem with installing ruby, and use Google Search to find this issue, excuse me, thank you!

**Comment by 4ndv** [comment]
> > And if you don't understand russian, why do you need to download anything from readmanga/mintmanga? Is there any non-russian manga on them?
> 
> I just have a problem with installing ruby, and use Google Search to find this issue, excuse me, thank you!

Glad to help!
