### ISSUE TITLE
Не скачивает мангу

### ISSUE THREAD

**Issue by panchenko9b** [4ndv/mrmanga#6]
Добрый день, при попытке скачать мангу http://readmanga.me/black_butler
происходит ошибка.
Другие манги, вроде, качает нормально.
Спасибо за ответ.
![image](https://user-images.githubusercontent.com/44533357/47671837-26baa900-dbb9-11e8-8ed4-e75c28f80e3a.png)

**Comment by 4ndv** [comment]
Благодарю за репорт, скорее всего проблема в спецсимволах в url, посмотрю

**Comment by 4ndv** [comment]
Пофиксил, пожалуйста обновите через `gem update mrmanga`
