### ISSUE TITLE
Не качает мангу

### ISSUE THREAD

**Issue by panchenko9b** [4ndv/mrmanga#8]
Добрый день. 
На ридманге не качает мангу, пишет Parsing manga info
Parsed, downloading, но ничего при этом не качается.
На минтманге сменился адрес https://mintmanga.live/, программа пишет, что неверно задана ссылка.

**Comment by 4ndv** [comment]
Проблема была в редиректе на https, плюс добавил новый домен. Новая версия уже в rubygems, обновлять вот так:

```
gem update mrmanga
```

Версия после обновления должна быть 0.12.0 или выше
